http:
  port: "8081"
  
american:
  host: "training4-american-api-aa-18112019.us-e2.cloudhub.io"
  port: "80"
  basepath: "/"
  protocol: "HTTP"
  client_id: "0fc38163d8bf48f28a9b004e06ab2763"
  client_secret: "2986Cead7B2344368883D2CA1B299f4d"
  
united:
  host: "ilt.learn.mulesoft.com"
  port: "80"
  basepath: "/"
  protocol: "HTTP"

delta:
  wsdl: "http://ilt.learn.mulesoft.com/delta?wsdl"
  service: "TicketServiceService"
  port: "TicketServicePort"

  